name: Linux CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  release_linux:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal:latest-alpine
    steps:
      - name: Install packages
        run: |
          apk add readline unibilium unibilium-dev
          ln -s /usr/lib/x86_64-alpine-linux-musl/libreadline.so.8 /usr/lib/x86_64-alpine-linux-musl/libreadline.so
      - name: Download source
        uses: actions/checkout@v2
      - name: Build binaries
        run: |
          shards update --production --release --static --no-debug
          crystal build --time --release --static --no-debug -o bin/tech-demo examples/tech-demo.cr
          crystal build --time --release --static --no-debug -o bin/hello examples/hello.cr
          crystal build --time --release --static --no-debug -o bin/hello2 examples/hello2.cr
